/**
 * Single source of truth for vacation packages
 * Used by both AI Agent and Merchant Agent
 */

import { VacationPackage } from "../types/ap2";

export type { VacationPackage };

export const VACATION_PACKAGES: VacationPackage[] = [
  {
    id: "vac-001",
    name: "Bali Paradise Retreat",
    destination: "Bali, Indonesia",
    region: "Asia",
    activities: ["beach", "luxury", "spa", "culture"],
    description: "7 days of luxury in a 5-star beachfront resort with daily spa treatments, gourmet dining, and guided temple tours",
    duration_days: 7,
    includes: ["5-star resort", "Daily breakfast & dinner", "Spa treatments", "Airport transfers", "Temple tours"],
    image_url: "/static/vacation/bali.jpg",
    price: 2499,
    currency: "USD",
    available_dates: ["2025-11-01", "2025-11-15", "2025-12-01"],
  },
  {
    id: "vac-002",
    name: "Maldives Overwater Villa",
    destination: "Maldives",
    region: "Asia",
    activities: ["beach", "luxury", "water-sports", "relaxation"],
    description: "5 nights in an exclusive overwater villa with private infinity pool, snorkeling, and sunset cruises",
    duration_days: 5,
    includes: ["Overwater villa", "All meals included", "Water sports", "Sunset cruise", "Spa access"],
    image_url: "/static/vacation/maldives.jpg",
    price: 3999,
    currency: "USD",
    available_dates: ["2025-10-20", "2025-11-10", "2025-12-05"],
  },
  {
    id: "vac-003",
    name: "Costa Rica Adventure",
    destination: "Costa Rica",
    region: "Central America",
    activities: ["adventure", "nature", "beach", "eco-tourism"],
    description: "10 days of eco-adventures including zip-lining, rainforest tours, volcano visits, and beach relaxation",
    duration_days: 10,
    includes: ["Eco-lodge stay", "Guided adventures", "All meals", "Equipment rental", "National park passes"],
    image_url: "/static/vacation/costa-rica.jpg",
    price: 1899,
    currency: "USD",
    available_dates: ["2025-10-15", "2025-11-01", "2025-11-20"],
  },
  {
    id: "vac-004",
    name: "Santorini Sunset Romance",
    destination: "Santorini, Greece",
    region: "Europe",
    activities: ["beach", "luxury", "romance", "culture", "wine"],
    description: "6 nights in a cave house with caldera views, wine tasting, sunset sailing, and authentic Greek cuisine",
    duration_days: 6,
    includes: ["Cave house accommodation", "Wine tours", "Sunset sailing", "Cooking class", "Island tour"],
    image_url: "/static/vacation/santorini.jpg",
    price: 2799,
    currency: "USD",
    available_dates: ["2025-10-10", "2025-11-05", "2025-12-15"],
  },
  {
    id: "vac-005",
    name: "Japanese Alps Winter Escape",
    destination: "Nagano, Japan",
    region: "Asia",
    activities: ["winter", "skiing", "culture", "hot-springs"],
    description: "5 days in a traditional ryokan with hot springs, skiing, and cultural experiences including tea ceremony",
    duration_days: 5,
    includes: ["Ryokan stay", "Hot springs access", "Ski pass", "Tea ceremony", "Traditional meals"],
    image_url: "/static/vacation/japan-alps.jpg",
    price: 2299,
    currency: "USD",
    available_dates: ["2025-12-10", "2025-12-20", "2026-01-05"],
  },
  {
    id: "vac-006",
    name: "Serengeti Safari Adventure",
    destination: "Serengeti, Tanzania",
    region: "Africa",
    activities: ["safari", "wildlife", "adventure", "nature"],
    description: "8 days witnessing the great migration, luxury tented camps, daily game drives, and hot air balloon safari",
    duration_days: 8,
    includes: ["Luxury tented camp", "All meals", "Game drives", "Hot air balloon safari", "Professional guide"],
    image_url: "/static/vacation/serengeti.jpg",
    price: 4299,
    currency: "USD",
    available_dates: ["2025-10-25", "2025-11-15", "2025-12-01"],
  },
  {
    id: "vac-007",
    name: "Marrakech & Sahara Desert",
    destination: "Morocco",
    region: "Africa",
    activities: ["culture", "adventure", "desert", "luxury"],
    description: "7 days exploring ancient medinas, luxury riad stay, camel trekking, and overnight in desert camps under the stars",
    duration_days: 7,
    includes: ["Riad accommodation", "Desert camp stay", "Camel trek", "Guided tours", "Traditional meals"],
    image_url: "/static/vacation/morocco.jpg",
    price: 1999,
    currency: "USD",
    available_dates: ["2025-10-15", "2025-11-10", "2025-12-05"],
  },
  {
    id: "vac-008",
    name: "Patagonia Wilderness Trek",
    destination: "Patagonia, Argentina & Chile",
    region: "South America",
    activities: ["hiking", "adventure", "nature", "glaciers"],
    description: "12 days exploring Torres del Paine, glacier trekking, mountain lodges, and breathtaking Andean landscapes",
    duration_days: 12,
    includes: ["Mountain lodge stays", "Guided treks", "All meals", "Park permits", "Ground transportation"],
    image_url: "/static/vacation/patagonia.jpg",
    price: 3499,
    currency: "USD",
    available_dates: ["2025-11-01", "2025-11-20", "2025-12-10"],
  },
  {
    id: "vac-009",
    name: "Machu Picchu & Amazon",
    destination: "Peru",
    region: "South America",
    activities: ["culture", "adventure", "history", "nature"],
    description: "10 days combining ancient Incan ruins, Sacred Valley exploration, and Amazon rainforest lodge experience",
    duration_days: 10,
    includes: ["Hotel & lodge stays", "Machu Picchu entry", "Train tickets", "Amazon excursions", "Local guides"],
    image_url: "/static/vacation/peru.jpg",
    price: 2899,
    currency: "USD",
    available_dates: ["2025-10-18", "2025-11-08", "2025-11-25"],
  },
  {
    id: "vac-010",
    name: "Great Barrier Reef Discovery",
    destination: "Queensland, Australia",
    region: "Australia/Oceania",
    activities: ["beach", "diving", "nature", "water-sports"],
    description: "7 days exploring the world's largest coral reef system with diving, snorkeling, and island hopping",
    duration_days: 7,
    includes: ["Beachfront resort", "Diving & snorkeling", "Boat tours", "Equipment rental", "Marine park fees"],
    image_url: "/static/vacation/great-barrier-reef.jpg",
    price: 3199,
    currency: "USD",
    available_dates: ["2025-10-22", "2025-11-12", "2025-12-03"],
  },
  {
    id: "vac-011",
    name: "New Zealand Fjordland",
    destination: "South Island, New Zealand",
    region: "Australia/Oceania",
    activities: ["nature", "adventure", "hiking", "scenic"],
    description: "9 days in Middle Earth - Milford Sound cruises, hobbit tours, glacier walks, and alpine adventures",
    duration_days: 9,
    includes: ["Hotel stays", "Milford Sound cruise", "Guided tours", "Glacier walks", "Hobbiton entry"],
    image_url: "/static/vacation/new-zealand.jpg",
    price: 3699,
    currency: "USD",
    available_dates: ["2025-11-05", "2025-11-25", "2025-12-15"],
  },
  {
    id: "vac-012",
    name: "Canadian Rockies Adventure",
    destination: "Alberta & British Columbia, Canada",
    region: "North America",
    activities: ["nature", "hiking", "wildlife", "scenic"],
    description: "8 days in Banff and Jasper National Parks with turquoise lakes, mountain lodges, and wildlife viewing",
    duration_days: 8,
    includes: ["Mountain lodge stays", "Park passes", "Guided hikes", "Lake cruises", "Wildlife tours"],
    image_url: "/static/vacation/canadian-rockies.jpg",
    price: 2599,
    currency: "USD",
    available_dates: ["2025-10-12", "2025-11-01", "2025-11-18"],
  },
  {
    id: "vac-013",
    name: "Alaskan Glacier Cruise",
    destination: "Alaska, USA",
    region: "North America",
    activities: ["cruise", "wildlife", "glaciers", "nature"],
    description: "10 days sailing through Inside Passage, glacier viewing, whale watching, and exploring frontier towns",
    duration_days: 10,
    includes: ["Luxury cruise ship", "All meals onboard", "Shore excursions", "Glacier tours", "Onboard entertainment"],
    image_url: "/static/vacation/alaska.jpg",
    price: 3899,
    currency: "USD",
    available_dates: ["2025-10-20", "2025-11-03", "2025-11-17"],
  },
  {
    id: "vac-014",
    name: "Swiss Alps Luxury Escape",
    destination: "Zermatt, Switzerland",
    region: "Europe",
    activities: ["skiing", "luxury", "mountain", "scenic"],
    description: "6 days in a chalet with Matterhorn views, world-class skiing, gourmet dining, and alpine spa treatments",
    duration_days: 6,
    includes: ["Luxury chalet", "Ski passes", "Spa treatments", "Gourmet meals", "Mountain railway tickets"],
    image_url: "/static/vacation/swiss-alps.jpg",
    price: 4499,
    currency: "USD",
    available_dates: ["2025-12-15", "2025-12-22", "2026-01-10"],
  },
  {
    id: "vac-015",
    name: "Iceland Northern Lights",
    destination: "Iceland",
    region: "Europe",
    activities: ["nature", "adventure", "northern-lights", "hot-springs"],
    description: "7 days chasing aurora borealis, exploring ice caves, soaking in Blue Lagoon, and visiting waterfalls",
    duration_days: 7,
    includes: ["Hotel stays", "Northern lights tours", "Blue Lagoon entry", "Ice cave tours", "4x4 transportation"],
    image_url: "/static/vacation/iceland.jpg",
    price: 2999,
    currency: "USD",
    available_dates: ["2025-12-05", "2025-12-18", "2026-01-08"],
  },
  {
    id: "vac-016",
    name: "Zakopane Mountain Retreat",
    destination: "Zakopane, Poland",
    region: "Europe",
    activities: ["skiing", "hiking", "culture", "mountain"],
    description: "6 days in the Polish Tatra Mountains with traditional wooden architecture, highland culture, skiing, and thermal baths",
    duration_days: 6,
    includes: ["Mountain hotel", "Ski pass", "Thermal baths access", "Highland folklore show", "Guided mountain tours"],
    image_url: "/static/vacation/zakopane.jpg",
    price: 1499,
    currency: "USD",
    available_dates: ["2025-12-01", "2025-12-15", "2026-01-05"],
  },
];

